services:
    - type: web
    name: teddyxmd-support
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: node index.js  # <-- CHANGED
    autoDeploy: true
    healthCheckPath: /
    
    envVars:
            - key: NODE_ENV
        value: production
            - key: PORT
        value: 50900
            - key: COMPANY_NAME
        value: TEDDY-XMD Support
            - key: ADMIN_KEY
        generateValue: true
            - key: MONGO_URI
        sync: false
            - key: BOT_TOKEN
        sync: false
            - key: ADMIN_IDS
        sync: false
            - key: OUTLOOK_EMAIL
        sync: false
            - key: OUTLOOK_PASS
        sync: false
